CREATE TABLE stocks (
    ID BIGINT PRIMARY KEY,
    Name TEXT NOT NULL,
    Price REAL NOT NULL,
    Company TEXT NOT NULL,
    Created_At TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);