// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Stock struct {
	ID        int32
	Name      string
	Price     pgtype.Numeric
	Company   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
