// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stock.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStock = `-- name: CreateStock :one
INSERT INTO stocks (
    Name, Price, Company
) VALUES (
    $1, $2, $3
)
RETURNING id, name, price, company, created_at, updated_at
`

type CreateStockParams struct {
	Name    string
	Price   pgtype.Numeric
	Company string
}

func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error) {
	row := q.db.QueryRow(ctx, createStock, arg.Name, arg.Price, arg.Company)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Company,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStock = `-- name: DeleteStock :exec
DELETE FROM stocks
WHERE ID = $1
`

func (q *Queries) DeleteStock(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteStock, id)
	return err
}

const getStock = `-- name: GetStock :one
SELECT id, name, price, company, created_at, updated_at FROM stocks
WHERE ID = $1 LIMIT 1
`

func (q *Queries) GetStock(ctx context.Context, id int32) (Stock, error) {
	row := q.db.QueryRow(ctx, getStock, id)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Company,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockByName = `-- name: GetStockByName :one
SELECT id, name, price, company, created_at, updated_at FROM stocks WHERE name = $1 LIMIT 1
`

func (q *Queries) GetStockByName(ctx context.Context, name string) (Stock, error) {
	row := q.db.QueryRow(ctx, getStockByName, name)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Company,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStocks = `-- name: ListStocks :many
SELECT id, name, price, company, created_at, updated_at FROM stocks
ORDER BY Name
`

func (q *Queries) ListStocks(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.Query(ctx, listStocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Company,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStock = `-- name: UpdateStock :exec
UPDATE stocks
SET 
    name = COALESCE($2, name),
    price = COALESCE($3, price),
    company = COALESCE($4, company),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, price, company, created_at, updated_at
`

type UpdateStockParams struct {
	ID      int32
	Name    string
	Price   pgtype.Numeric
	Company string
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) error {
	_, err := q.db.Exec(ctx, updateStock,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Company,
	)
	return err
}
