CREATE TABLE stocks (
    ID BIGINT PRIMARY KEY,
    Name TEXT NOT NULL,
    Price REAL NOT NULL,
    Company TEXT NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);